version: 2.0

jobs:
  build:
    docker:
      - image: registry.opensuse.org/opensuse/tumbleweed
    steps:
      - checkout
      - run:
          command: |
            zypper -n in --no-recommends make python3 tar git-core || :
      - checkout
      - run: make test_regen_all
      - run: make test
