version: 2.1

jobs:
  unit:
    docker:
      - image: registry.opensuse.org/devel/openqa/openqa-trigger-from-obs/containers/openqa-trigger-from-obs-dev
    steps:
      - checkout
      - run: make test_regen_all
      - run: make test

  style:
    docker:
      - image: registry.opensuse.org/devel/openqa/openqa-trigger-from-obs/containers/openqa-trigger-from-obs-dev
    steps:
      - checkout
      - run: make test_python_style

workflows:
  test:
    jobs:
      - unit
      - style
