version: 2.1

jobs:
  unit:
    docker:
      - image: registry.opensuse.org/opensuse/tumbleweed
    steps:
      - checkout
      - run:
          command: |
            zypper -n in --no-recommends diffutils make python3 tar
      - checkout
      - run: make test_regen_all
      - run: make test

  integration:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          command: |
            pyenv versions
            pyenv global 3.7.0
            git clone https://github.com/coryb/osht ../osht
            docker pull registry.opensuse.org/devel/openqa/ci/containers/serviced
            sudo chown -R 1000:1000 .
            make test_docker PRIVILEGED_TESTS=1 OSHT_LOCATION=$(pwd)/../osht/osht.sh

workflows:
  version: 2.1
  test:
    jobs:
      - unit
      - integration
