version: 2.1

jobs:
  unit:
    docker:
      - image: registry.opensuse.org/opensuse/leap:15.5
    steps:
      - checkout
      - run:
          command: |
            zypper -n in --no-recommends diffutils make python3 tar git-core
      - checkout
      - run: git clean -df
      - run: make test_regen_all
      - run: make test

  style:
    docker:
      - image: registry.opensuse.org/opensuse/tumbleweed
    steps:
      - checkout
      - run:
          command: |
            zypper -n in --no-recommends make python3-black python3-importlib-metadata
      - checkout
      - run: make test_python_style

workflows:
  version: 2.1
  test:
    jobs:
      - unit
      - style
