---
name: CI

on: [pull_request, workflow_dispatch]  # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: integration
        run: |
          podman pull registry.opensuse.org/devel/openqa/ci/containers/serviced
          make test_docker PRIVILEGED_TESTS=1
